package hibernate;
// Generated 2016-12-13 10:58:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ArtCommentId generated by hbm2java
 */
@Embeddable
public class ArtCommentId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int commentatorId;
	private int comArtId;

	public ArtCommentId() {
	}

	public ArtCommentId(int commentatorId, int comArtId) {
		this.commentatorId = commentatorId;
		this.comArtId = comArtId;
	}

	@Column(name = "commentator_id", nullable = false)
	public int getCommentatorId() {
		return this.commentatorId;
	}

	public void setCommentatorId(int commentatorId) {
		this.commentatorId = commentatorId;
	}

	@Column(name = "com_art_id", nullable = false)
	public int getComArtId() {
		return this.comArtId;
	}

	public void setComArtId(int comArtId) {
		this.comArtId = comArtId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArtCommentId))
			return false;
		ArtCommentId castOther = (ArtCommentId) other;

		return (this.getCommentatorId() == castOther.getCommentatorId())
				&& (this.getComArtId() == castOther.getComArtId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommentatorId();
		result = 37 * result + this.getComArtId();
		return result;
	}

}
