package hibernate;
// Generated 2016-12-13 10:58:38 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArtComment generated by hbm2java
 */
@Entity
@Table(name = "art_comment", catalog = "db_15")
public class ArtComment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ArtCommentId id;
	private Article article;
	private User user;
	private Date artComTime;
	private String artComContent;

	public ArtComment() {
	}

	public ArtComment(ArtCommentId id, Article article, User user) {
		this.id = id;
		this.article = article;
		this.user = user;
	}

	public ArtComment(ArtCommentId id, Article article, User user, Date artComTime, String artComContent) {
		this.id = id;
		this.article = article;
		this.user = user;
		this.artComTime = artComTime;
		this.artComContent = artComContent;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "commentatorId", column = @Column(name = "commentator_id", nullable = false) ),
			@AttributeOverride(name = "comArtId", column = @Column(name = "com_art_id", nullable = false) ) })
	public ArtCommentId getId() {
		return this.id;
	}

	public void setId(ArtCommentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "com_art_id", nullable = false, insertable = false, updatable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commentator_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "art_com_time", length = 10)
	public Date getArtComTime() {
		return this.artComTime;
	}

	public void setArtComTime(Date artComTime) {
		this.artComTime = artComTime;
	}

	@Column(name = "art_com_content", length = 200)
	public String getArtComContent() {
		return this.artComContent;
	}

	public void setArtComContent(String artComContent) {
		this.artComContent = artComContent;
	}

}
