package hibernate;
// Generated 2016-12-13 10:58:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReportId generated by hbm2java
 */
@Embeddable
public class ReportId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int repUserId;
	private int repArtId;

	public ReportId() {
	}

	public ReportId(int repUserId, int repArtId) {
		this.repUserId = repUserId;
		this.repArtId = repArtId;
	}

	@Column(name = "rep_user_id", nullable = false)
	public int getRepUserId() {
		return this.repUserId;
	}

	public void setRepUserId(int repUserId) {
		this.repUserId = repUserId;
	}

	@Column(name = "rep_art_id", nullable = false)
	public int getRepArtId() {
		return this.repArtId;
	}

	public void setRepArtId(int repArtId) {
		this.repArtId = repArtId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReportId))
			return false;
		ReportId castOther = (ReportId) other;

		return (this.getRepUserId() == castOther.getRepUserId()) && (this.getRepArtId() == castOther.getRepArtId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRepUserId();
		result = 37 * result + this.getRepArtId();
		return result;
	}

}
