package hibernate;
// Generated 2016-12-13 10:58:38 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ResMark generated by hbm2java
 */
@Entity
@Table(name = "res_mark", catalog = "db_15")
public class ResMark implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ResMarkId id;
	private User user;
	private Restaurant restaurant;
	private Date resMarkTime;
	private Integer resMark;

	public ResMark() {
	}

	public ResMark(ResMarkId id, User user, Restaurant restaurant) {
		this.id = id;
		this.user = user;
		this.restaurant = restaurant;
	}

	public ResMark(ResMarkId id, User user, Restaurant restaurant, Date resMarkTime, Integer resMark) {
		this.id = id;
		this.user = user;
		this.restaurant = restaurant;
		this.resMarkTime = resMarkTime;
		this.resMark = resMark;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "mresId", column = @Column(name = "mres_id", nullable = false) ),
			@AttributeOverride(name = "markerId", column = @Column(name = "marker_id", nullable = false) ) })
	public ResMarkId getId() {
		return this.id;
	}

	public void setId(ResMarkId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "marker_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mres_id", nullable = false, insertable = false, updatable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "res_mark_time", length = 10)
	public Date getResMarkTime() {
		return this.resMarkTime;
	}

	public void setResMarkTime(Date resMarkTime) {
		this.resMarkTime = resMarkTime;
	}

	@Column(name = "res_mark")
	public Integer getResMark() {
		return this.resMark;
	}

	public void setResMark(Integer resMark) {
		this.resMark = resMark;
	}

}
