package hibernate;
// Generated 2016-12-13 10:58:38 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RouTradeId generated by hbm2java
 */
@Embeddable
public class RouTradeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int tradeUserId;
	private int tradeRouId;

	public RouTradeId() {
	}

	public RouTradeId(int tradeUserId, int tradeRouId) {
		this.tradeUserId = tradeUserId;
		this.tradeRouId = tradeRouId;
	}

	@Column(name = "trade_user_id", nullable = false)
	public int getTradeUserId() {
		return this.tradeUserId;
	}

	public void setTradeUserId(int tradeUserId) {
		this.tradeUserId = tradeUserId;
	}

	@Column(name = "trade_rou_id", nullable = false)
	public int getTradeRouId() {
		return this.tradeRouId;
	}

	public void setTradeRouId(int tradeRouId) {
		this.tradeRouId = tradeRouId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RouTradeId))
			return false;
		RouTradeId castOther = (RouTradeId) other;

		return (this.getTradeUserId() == castOther.getTradeUserId())
				&& (this.getTradeRouId() == castOther.getTradeRouId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTradeUserId();
		result = 37 * result + this.getTradeRouId();
		return result;
	}

}
