package hibernate;
// Generated 2016-12-13 10:58:38 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Route generated by hbm2java
 */
@Entity
@Table(name = "route", catalog = "db_15")
public class Route implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rouId;
	private User user;
	private String rouTitle;
	private String rouTitlePic;
	private String rouContent;
	private String rouAddrProvince;
	private String rouAddrCity;
	private Integer rouPrice;
	private Date rouPostTime;
	private Character rouStatus;
	private Set<RouTrade> rouTrades = new HashSet<RouTrade>(0);

	public Route() {
	}

	public Route(User user, String rouTitle, String rouTitlePic, String rouContent, String rouAddrProvince,
			String rouAddrCity, Integer rouPrice, Date rouPostTime, Character rouStatus, Set<RouTrade> rouTrades) {
		this.user = user;
		this.rouTitle = rouTitle;
		this.rouTitlePic = rouTitlePic;
		this.rouContent = rouContent;
		this.rouAddrProvince = rouAddrProvince;
		this.rouAddrCity = rouAddrCity;
		this.rouPrice = rouPrice;
		this.rouPostTime = rouPostTime;
		this.rouStatus = rouStatus;
		this.rouTrades = rouTrades;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rou_id", unique = true, nullable = false)
	public Integer getRouId() {
		return this.rouId;
	}

	public void setRouId(Integer rouId) {
		this.rouId = rouId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rou_user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "rou_title", length = 30)
	public String getRouTitle() {
		return this.rouTitle;
	}

	public void setRouTitle(String rouTitle) {
		this.rouTitle = rouTitle;
	}

	@Column(name = "rou_title_pic", length = 100)
	public String getRouTitlePic() {
		return this.rouTitlePic;
	}

	public void setRouTitlePic(String rouTitlePic) {
		this.rouTitlePic = rouTitlePic;
	}

	@Column(name = "rou_content", length = 65535)
	public String getRouContent() {
		return this.rouContent;
	}

	public void setRouContent(String rouContent) {
		this.rouContent = rouContent;
	}

	@Column(name = "rou_addr_province", length = 20)
	public String getRouAddrProvince() {
		return this.rouAddrProvince;
	}

	public void setRouAddrProvince(String rouAddrProvince) {
		this.rouAddrProvince = rouAddrProvince;
	}

	@Column(name = "rou_addr_city", length = 20)
	public String getRouAddrCity() {
		return this.rouAddrCity;
	}

	public void setRouAddrCity(String rouAddrCity) {
		this.rouAddrCity = rouAddrCity;
	}

	@Column(name = "rou_price")
	public Integer getRouPrice() {
		return this.rouPrice;
	}

	public void setRouPrice(Integer rouPrice) {
		this.rouPrice = rouPrice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rou_post_time", length = 10)
	public Date getRouPostTime() {
		return this.rouPostTime;
	}

	public void setRouPostTime(Date rouPostTime) {
		this.rouPostTime = rouPostTime;
	}

	@Column(name = "rou_status", length = 1)
	public Character getRouStatus() {
		return this.rouStatus;
	}

	public void setRouStatus(Character rouStatus) {
		this.rouStatus = rouStatus;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "route")
	public Set<RouTrade> getRouTrades() {
		return this.rouTrades;
	}

	public void setRouTrades(Set<RouTrade> rouTrades) {
		this.rouTrades = rouTrades;
	}

}
