package hibernate;
// Generated 2016-12-13 10:58:38 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "db_15")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String userName;
	private String userTel;
	private String userPassword;
	private Integer userLevel;
	private Integer userExperience;
	private Integer userMoney;
	private Character userCertStatus;
	private Character userGender;
	private Integer userBirthYear;
	private Date userRegTime;
	private String userBpCity;
	private String userBpProvince;
	private String userLpCity;
	private String userLpProvince;
	private Set<Report> reports = new HashSet<Report>(0);
	private Set<ResMark> resMarks = new HashSet<ResMark>(0);
	private Set<ArtComment> artComments = new HashSet<ArtComment>(0);
	private Set<Article> articles = new HashSet<Article>(0);
	private Set<Restaurant> restaurants = new HashSet<Restaurant>(0);
	private Set<RouTrade> rouTrades = new HashSet<RouTrade>(0);
	private Set<Route> routes = new HashSet<Route>(0);
	private Set<Article> articles_1 = new HashSet<Article>(0);

	public User() {
	}

	public User(String userName, String userTel, String userPassword, Integer userLevel, Integer userExperience,
			Integer userMoney, Character userCertStatus, Character userGender, Integer userBirthYear, Date userRegTime,
			String userBpCity, String userBpProvince, String userLpCity, String userLpProvince, Set<Report> reports,
			Set<ResMark> resMarks, Set<ArtComment> artComments, Set<Article> articles, Set<Restaurant> restaurants,
			Set<RouTrade> rouTrades, Set<Route> routes, Set<Article> articles_1) {
		this.userName = userName;
		this.userTel = userTel;
		this.userPassword = userPassword;
		this.userLevel = userLevel;
		this.userExperience = userExperience;
		this.userMoney = userMoney;
		this.userCertStatus = userCertStatus;
		this.userGender = userGender;
		this.userBirthYear = userBirthYear;
		this.userRegTime = userRegTime;
		this.userBpCity = userBpCity;
		this.userBpProvince = userBpProvince;
		this.userLpCity = userLpCity;
		this.userLpProvince = userLpProvince;
		this.reports = reports;
		this.resMarks = resMarks;
		this.artComments = artComments;
		this.articles = articles;
		this.restaurants = restaurants;
		this.rouTrades = rouTrades;
		this.routes = routes;
		this.articles_1 = articles_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_tel", length = 11)
	public String getUserTel() {
		return this.userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	@Column(name = "user_password", length = 20)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_level")
	public Integer getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(Integer userLevel) {
		this.userLevel = userLevel;
	}

	@Column(name = "user_experience")
	public Integer getUserExperience() {
		return this.userExperience;
	}

	public void setUserExperience(Integer userExperience) {
		this.userExperience = userExperience;
	}

	@Column(name = "user_money")
	public Integer getUserMoney() {
		return this.userMoney;
	}

	public void setUserMoney(Integer userMoney) {
		this.userMoney = userMoney;
	}

	@Column(name = "user_cert_status", length = 1)
	public Character getUserCertStatus() {
		return this.userCertStatus;
	}

	public void setUserCertStatus(Character userCertStatus) {
		this.userCertStatus = userCertStatus;
	}

	@Column(name = "user_gender", length = 1)
	public Character getUserGender() {
		return this.userGender;
	}

	public void setUserGender(Character userGender) {
		this.userGender = userGender;
	}

	@Column(name = "user_birth_year")
	public Integer getUserBirthYear() {
		return this.userBirthYear;
	}

	public void setUserBirthYear(Integer userBirthYear) {
		this.userBirthYear = userBirthYear;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "user_reg_time", length = 10)
	public Date getUserRegTime() {
		return this.userRegTime;
	}

	public void setUserRegTime(Date userRegTime) {
		this.userRegTime = userRegTime;
	}

	@Column(name = "user_bp_city", length = 20)
	public String getUserBpCity() {
		return this.userBpCity;
	}

	public void setUserBpCity(String userBpCity) {
		this.userBpCity = userBpCity;
	}

	@Column(name = "user_bp_province", length = 20)
	public String getUserBpProvince() {
		return this.userBpProvince;
	}

	public void setUserBpProvince(String userBpProvince) {
		this.userBpProvince = userBpProvince;
	}

	@Column(name = "user_lp_city", length = 20)
	public String getUserLpCity() {
		return this.userLpCity;
	}

	public void setUserLpCity(String userLpCity) {
		this.userLpCity = userLpCity;
	}

	@Column(name = "user_lp_province", length = 20)
	public String getUserLpProvince() {
		return this.userLpProvince;
	}

	public void setUserLpProvince(String userLpProvince) {
		this.userLpProvince = userLpProvince;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ResMark> getResMarks() {
		return this.resMarks;
	}

	public void setResMarks(Set<ResMark> resMarks) {
		this.resMarks = resMarks;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ArtComment> getArtComments() {
		return this.artComments;
	}

	public void setArtComments(Set<ArtComment> artComments) {
		this.artComments = artComments;
	}

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinTable(name = "art_like", catalog = "db_15", joinColumns = {
			@JoinColumn(name = "liker_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "like_art_id", nullable = false, updatable = false) })
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinTable(name = "res_collect", catalog = "db_15", joinColumns = {
			@JoinColumn(name = "collector_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "cres_id", nullable = false, updatable = false) })
	public Set<Restaurant> getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Set<Restaurant> restaurants) {
		this.restaurants = restaurants;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
	public Set<RouTrade> getRouTrades() {
		return this.rouTrades;
	}

	public void setRouTrades(Set<RouTrade> rouTrades) {
		this.rouTrades = rouTrades;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Route> getRoutes() {
		return this.routes;
	}

	public void setRoutes(Set<Route> routes) {
		this.routes = routes;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Article> getArticles_1() {
		return this.articles_1;
	}

	public void setArticles_1(Set<Article> articles_1) {
		this.articles_1 = articles_1;
	}

}
